### ISSUE TITLE
Dynmaps doesn't load all maps from the dynmaps folder.

### ISSUE THREAD

**Issue by GeraltV47** [askuri/dynmaps#15]
What it could be caused by? records-eyepiece shows all 1795 tracks in my dynmaps folder but after using command /dyn_cacherefresh there are only 1789 loaded. What can cause this issue? Edit: records-eyepiece shows only 1793 tracks when in dynmaps folder i got 1794 tracks. When i type command /list env:island there is only 1788 tracks shown.

**Comment by askuri** [comment]
Is it possible that there are some tracks that are invalid or incompatible with your server (like Coast on an island-only-server)? Do some of the tracks have a filename containing other characters than a-z and 0-9? Are there tracks in subfolders in dynmaps folder? 

> but after using command /dyn_cacherefresh there are only 1789 loaded

Where does it say 1789 then? Also in Records Eyepiece?

**Comment by GeraltV47** [comment]
No, all my tracks are island only and are in dynmaps folder, i got some with ( ) but when i type their name by /list command they are shown in the window. 1789, is displayed on chat after reloading dynmaps cache. Records Eyepiece shows more tracks.

**Comment by askuri** [comment]
Then try to see if you find something in dyn_loading_errors.txt or on the console output of xaseco.

Make sure all your Tracks follow this filename pattern:
`*.[Cc]hallenge.[Gg]bx`

**Comment by GeraltV47** [comment]
All track seems to fulfill this pattern, dyn_loading_errors show all errors from tracks i deleted, and dont show errors anymore

**Comment by GeraltV47** [comment]
OK it turned out that one track was coast, i erased it but still eyepiece shows 1 track less than i have in dynmaps folder also when i type /dyn_cacherefresh it display 1787 tracks only, records-eyepiece shows 1790 tracks.

**Comment by GeraltV47** [comment]
is that related to dynmaps? maybe some error? how is that possible that eyepiece shows all tracks and dynmaps load almost all of them?

**Comment by askuri** [comment]
I honestly don't know what else it could be then. Would require some testing on my end, but I currently don't have the time to do that, unfortunately.

I should probably say again that this mod is mostly unmaintained and is provided as-is. Anyone can contribute and I'm willing to transfer the repository to someone else, but I don't think I'll develop it further, sorry.
