### ISSUE TITLE
Problem with old usbTMFserver 2.9 by SSRlille79

### ISSUE THREAD

**Issue by pete9516** [askuri/dynmaps#21]
ello guys,
i have a very old usbTMFserver. With well over 10k maps. So i want to use this nice plugin, but there is a problem when running xaseco.
![image](https://user-images.githubusercontent.com/57021949/129495590-c2c3b5c2-5e17-4af5-9136-2db619113cb7.png)
I already have the newest version of xaseco (i think). Somebody gave me his version which works with his server and this plugin. Do you have any ideas? Help would be much appreciated.
Cheers

**Comment by pete9516** [comment]
![image](https://user-images.githubusercontent.com/57021949/129495642-e36a5fe7-260e-4c17-8bb3-9f6621d007f1.png)

**Comment by pete9516** [comment]
For some reason xaseco won't load the rasp plugins first...
![image](https://user-images.githubusercontent.com/57021949/129496425-0992edb5-164f-4d36-82b7-25c3ae81964b.png)

**Comment by askuri** [comment]
Hello,

Which PHP version are you using? To find out, look at the Xaseco log just before it loads the plugins: `[XAseco] PHP Version is X.Y.Z on WINNT`

I believe you have PHP 5, while PHP 7 is required for this.

**Comment by pete9516** [comment]
> Hello,
> 
> Which PHP version are you using? To find out, look at the Xaseco log just before it loads the plugins: `[XAseco] PHP Version is X.Y.Z on WINNT`
> 
> I believe you have PHP 5, while PHP 7 is required for this.

![image](https://user-images.githubusercontent.com/57021949/129601017-50617743-120c-4780-9c10-2d391df3d2c2.png)
Do you think it's possible to port the new version of PHP into the old one? Because i actually want my server to stay portable. I already know that with ampps it would probably work, but i don't like to play with sql databases. The problem is, when i replace PHP 5.3.5. with some newer version (i think it was 5.6) apache won't run anymore.. :/

**Comment by askuri** [comment]
Indeed, replacing PHP in Mowes is not as easy as that. However, upgrading PHP is still possible. In fact, I realized we had this very same issue also with usbTMFserver in issue #9 and NoTimeToDrive was able to fix it.

I can offer you personal assistance with this issue probably next week. If you haven't fixed it by 23.09.2021, you can send me an email: enwi2@t-online.de
