### ISSUE TITLE
/dyn_cacherefresh doesn't add track to cache

### ISSUE THREAD

**Issue by dassschaf** [askuri/dynmaps#4]
I added a new track into the folder (the correct folder this time...) and with /dyn_cacherefresh it won't get added to the cache.

I looked up the source already, calling the command calls `$dyn->cacheRefresh`, which will call a function in the rasp.funcs.php, which itself calls the `$dyn->emulateGetChallengeList` function that only looks up hte GBX header info from the existing tracks instead of looking for new tracks.

(I hope this time it's not again me doing something wrong.)

**Comment by askuri** [comment]
Works for me without any problems. I can add and remove tracks.
Make sure there's no typo in the command as xaseco doesn't warn you about non-existant commands.
If it's working, you should first see a red warning message in chat saying xaseco might hang for a minute, then after the green confirmation how many tracks were loaded.

**Comment by dassschaf** [comment]
I do get said warnings and the command works, however I added a track into the correct folder and it only appeared after restarting XAseco, not via /dyn_cacherefresh.
The track would not appear in /list and the number of tracks did not change before and after adding a track.

**Comment by NoTimeToDrive** [comment]
No comment so far ;)

Only a very big thanks for making this tool!!
If the bug is fixed.
I will use it for sure!!
Thanks thanks and thanks :)

Greetings

**Comment by askuri** [comment]
Thank you, NoTimeToDrive.

For the record of this issue: the problem occurs when setting startup refresh in the settings to true. If it is set to false, refresh I game works without any problems. For a production setup, startup refresh is not recommended anyway, because it makes the xaseco start take way longer.
